# Generated by Django 4.1.7 on 2023-02-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_song_album_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1.blog'),
        ),
    ]
