# Generated by Django 4.1.7 on 2023-02-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_article_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='blog',
        ),
        migrations.AddField(
            model_name='article',
            name='blogs',
            field=models.ManyToManyField(to='app1.blog'),
        ),
    ]
