# Generated by Django 4.1.7 on 2023-02-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_article_blog_article_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='blogs',
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.blog'),
        ),
    ]
