# Generated by Django 4.1.7 on 2023-02-19 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_article_blogs_article_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.blog'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='gjh'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subject',
            field=models.CharField(choices=[('s1', 'subject 1'), ('s2', 'subject 2'), ('s3', 'subject 3')], default='s2', max_length=50),
        ),
    ]
