# Generated by Django 4.1.7 on 2023-02-19 07:50

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(default=app1.models.get_blog, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.blog'),
        ),
    ]
