# Generated by Django 4.1.7 on 2023-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_article_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
