# Generated by Django 4.1.7 on 2023-02-19 18:09

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_article_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num',
            field=models.IntegerField(null=True, validators=[app1.models.validate_even]),
        ),
    ]
