# Generated by Django 4.1.7 on 2023-02-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_article_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(regex='[a-z]+')]),
        ),
    ]
