# Generated by Django 4.1.7 on 2023-02-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_article_content_alter_article_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
