# Generated by Django 4.1.7 on 2023-02-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_article_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(upload_to='uploaded_files')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to='uploaded_files'),
        ),
    ]
