# Generated by Django 4.1.7 on 2023-02-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
