# Generated by Django 4.1.7 on 2023-03-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
