# Generated by Django 4.1.7 on 2023-03-01 19:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='xc', editable=True, populate_from='name'),
        ),
    ]
