# Generated by Django 4.1.7 on 2023-03-02 18:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='xc', editable=True, populate_from='name', unique=True),
        ),
    ]
