# Generated by Django 4.1.7 on 2023-03-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_remove_person_file_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='image',
        ),
    ]
